Removes command that causes errors
`tmuxinator commands zsh` causes: 
ERROR: "tmuxinator commands" was called with arguments ["zsh"]
This commit removes the extra zsh commands and solves the problem.