fix: Revert rubygems ruby version to >= 2.6 (#976)
Fixes #974

Problem

The latest version of tmuxinator cannot be installed on system ruby on
macos:

```
$ sudo /usr/bin/gem install tmuxinator
ERROR:  Error installing tmuxinator:
        The last version of tmuxinator (>= 0) to support your Ruby & RubyGems was 3.3.4. Try installing it with `gem install tmuxinator -v 3.3.4` and then running the current command again
        tmuxinator requires Ruby version >= 2.7. The current ruby version is 2.6.10.210.
```

Solution

Set the required ruby version in the gemspec to be >= 2.6 instead of >= 2.7

Signed-off-by: Andrew Kofink <ajkofink@gmail.com>